FROM ubuntu:latest

USER root
RUN apt update -y
# Install Python and Pip
RUN apt install -y python3 && apt install -y python3-pip

# Install psycopg2-binary 
RUN pip install psycopg2-binary

# Create task_log file
RUN touch /task_log

# Copy gTS to the container
COPY ./build-resources/geocml-task-scheduler/geocml-task-scheduler/ /geocml-task-scheduler

######### Customize Container Here ###########
######### End Customizations ###########

CMD python3 /geocml-task-scheduler/schedule.py