FROM --platform=linux/amd64 ubuntu:22.04

USER root
WORKDIR /
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && apt update
RUN apt install -y nix postgresql postgis python3.11 python3-pip python3.11-venv python3.11-dev

RUN mkdir ./geocml-task-scheduler/
COPY ./build-resources/geocml-task-scheduler/make.sh ./make.sh

RUN chmod +x ./make.sh
RUN ./make.sh

ADD ./build-resources/geocml-task-scheduler/geocml-task-scheduler ./geocml-task-scheduler/geocml-task-scheduler/

######### Customize Container Here ###########
######### End Customizations ###########

RUN apt clean autoclean && apt autoremove -y && rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN nix-collect-garbage -d
RUN rm ./make.sh

COPY ./build-resources/geocml-task-scheduler/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
CMD ./entrypoint.sh
